# Missing Value Analysis

## Objective

To identify missing values in a dataset, calculate missing-value counts and percentages for each column, and identify columns that may require data cleaning before machine learning.

In [3]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Arun", "Priya", "Kavin", "Divya", "Rahul", "Meena"],
    "Age": [21, 22, np.nan, 23, 21, np.nan],
    "Marks": [85, np.nan, 78, 92, np.nan, 88],
    "Department": ["MCA", "BCA", "MCA", np.nan, "BCA", "MCA"]
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

Original Dataset:

    Name   Age  Marks Department
0   Arun  21.0   85.0        MCA
1  Priya  22.0    NaN        BCA
2  Kavin   NaN   78.0        MCA
3  Divya  23.0   92.0        NaN
4  Rahul  21.0    NaN        BCA
5  Meena   NaN   88.0        MCA

In [5]:
print("Missing Values in Each Column:")
print(df.isnull().sum())

Missing Values in Each Column:
Name          0
Age           2
Marks         2
Department    1
dtype: int64

In [6]:
total_missing = df.isnull().sum().sum()

print("Total Missing Values:", total_missing)

Total Missing Values: 5

In [7]:
missing_counts = df.isnull().sum()
missing_percentages = (missing_counts / len(df)) * 100

print("Missing Value Percentages:")
print(missing_percentages.round(2))

Missing Value Percentages:
Name           0.00
Age           33.33
Marks         33.33
Department    16.67
dtype: float64

In [8]:
missing_summary = pd.DataFrame({
    "Missing Count": missing_counts,
    "Missing Percentage": missing_percentages.round(2)
})

print("Missing Value Summary:")
display(missing_summary)

Missing Value Summary:

            Missing Count  Missing Percentage
Name                    0                0.00
Age                     2               33.33
Marks                   2               33.33
Department              1               16.67

In [9]:
columns_to_treat = missing_counts[missing_counts > 0].index.tolist()

print("Columns Requiring Missing-Value Treatment:")
print(columns_to_treat)

Columns Requiring Missing-Value Treatment:
['Age', 'Marks', 'Department']

In [10]:
if df.isnull().values.any():
    print("The dataset contains missing values.")
else:
    print("The dataset has no missing values.")

The dataset contains missing values.

In [11]:
print("Missing Value Analysis Report")
print("-----------------------------")
print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])
print("Total Missing Values:", total_missing)
print("Columns with Missing Values:", len(columns_to_treat))

print("\nColumn-wise Summary:")
display(missing_summary)

print("\nColumns Requiring Treatment:")
for column in columns_to_treat:
    print(column)

Missing Value Analysis Report
-----------------------------
Total Rows: 6
Total Columns: 4
Total Missing Values: 5
Columns with Missing Values: 3

Column-wise Summary:

            Missing Count  Missing Percentage
Name                    0                0.00
Age                     2               33.33
Marks                   2               33.33
Department              1               16.67

Columns Requiring Treatment:
Age
Marks
Department

## Observations

1. The dataset contains 6 rows and 4 columns.
2. There are 5 missing values in total.
3. The Age column contains 2 missing values, representing 33.33%.
4. The Marks column contains 2 missing values, representing 33.33%.
5. The Department column contains 1 missing value, representing 16.67%.
6. The Name column has no missing values.
7. Age, Marks, and Department may require missing-value treatment before machine learning.

## Conclusion

Missing-value analysis helps identify incomplete data before building machine learning models. Missing values can be handled using suitable methods, such as replacing values with the mean, median, or mode, or removing records when appropriate. The treatment method should depend on the dataset and the problem.